### ISSUE TITLE
Retain Input Fastqs

### ISSUE THREAD

**Issue by whottel** [CDCgov/NCHHSTP-DTBE-Varpipe-WGS#10]
Hello,

Is it necessary to delete the input fastqs from the data folder after the script finishes running?
This seems to occur whether or not the script actually ran correctly, making in time consuming to re-copy the desired input files.
Could the input fastqs be reatined in data/ or moved to another folder under data/ something like "fastq"?
If deletion of these files is deemed more appropriate, could the readme be more clear that this will occur when running runVarpipeline.sh? 

Thanks,
Wes

**Comment by reagank** [comment]
Retaining the input files should be something we can add - we will work on putting it in the next release

**Comment by whottel** [comment]
Sounds good thanks!

-Wes
