### ISSUE TITLE
bug  in the script "get_gatk.sh" 

### ISSUE THREAD

**Issue by ybdong919** [CDCgov/NCHHSTP-DTBE-Varpipe-WGS#3]
In the script "get_gatk.sh", "DL_URL=..." should be changed to "URL...".  Also, "mv gatk-package-4.2.4.0-local.jar ../tools/gatk-4.2.4.0/" should be changed to "mv ./gatk-4.2.4.0/gatk-package-4.2.4.0-local.jar ../tools/gatk-4.2.4.0/ "

The corrected script is shown below:

       #DL_URL='https://github.com/broadinstitute/gatk/releases/download/4.2.4.0/gatk-4.2.4.0.zip'
       URL='https://github.com/broadinstitute/gatk/releases/download/4.2.4.0/gatk-4.2.4.0.zip'    #debug
       mkdir tmp
       cd tmp
       wget -O- $URL >gatk-4.2.4.0.zip
       unzip gatk-4.2.4.0.zip

       #mv gatk-package-4.2.4.0-local.jar ../tools/gatk-4.2.4.0/
      mv ./gatk-4.2.4.0/gatk-package-4.2.4.0-local.jar ../tools/gatk-4.2.4.0/    #debug
      cd ../
      rm -rf tmp/

**Comment by reagank** [comment]
This should be fixed in commit 3279dcd
