### ISSUE TITLE
Optional Debug the script "Varpipeline.py" in /tools/ 

### ISSUE THREAD

**Issue by ybdong919** [CDCgov/NCHHSTP-DTBE-Varpipe-WGS#4]
The terminal sometimes shows " AttributeError: module 'yaml' has no attribute 'FullLoader' ".
In the above situation,  PyYAML version is probably too old. This was added in 5.1. But you can use yaml.Loader instead, it is an alias for FullLoader.

**Comment by reagank** [comment]
This should be corrected in the most recent commit - d396209
