### ISSUE TITLE
Singularity Installation Issues

### ISSUE THREAD

**Issue by whottel** [CDCgov/NCHHSTP-DTBE-Varpipe-WGS#8]
Hello, 

I tried following along with the readme and ran into several issues when trying to install via singularity.

First trying: `singularity pull library://reagank/varpipe_wgs/pipeline_with_refs`
I get the following error message: `Unable to get library client configuration: remote has no library client`

Next I tried cloning the repository and running: `./build_singularity.sh with_references`
And got this error message: `Unable to create build: failed to create build parent dir: stat /Users/hottel/.tmp: no such file or directory`

Looking at what the build_singularity.sh script was trying to do, I was able to run `singularity build pipeline_with_references.sif docker://ghcr.io/cdcgov/varpipe_wgs_with_refs:latest`, which installed the image to my working directory

Alternatively, I also ran `singularity pull docker://ghcr.io/cdcgov/varpipe_wgs_with_refs:latest`, and the image was downloaded to my working directory.

In either case I was unable to run `./runVarpipeline.sh`, looking into this with `singularity shell` I noticed that /varpipe_wgs/data did not contain runVarpipeline.sh. However, /varpipe_wgs/tools did seem to contain all the expected files. 

-Wes

**Comment by reagank** [comment]
Hi Wes,

This issue with the build script is the missing ~/.tmp directory. You can either remove the SINGULARITY_TMPDIR= from the beginning of that command or run `mkdir ~/.tmp`

As for the missing script, I think this may be an issue with how the data files are being mounted. We'll work on an update, but for the moment please try this:

 - Clone the repository and place your fastq files in the data directory
 - Run the shell command and make sure that you've bound the data directory to /varpipe_wgs/data
 - cd to /varpipe_wgs/data and run the script.

**Comment by whottel** [comment]
Thanks, I was able to run the script correctly using the method you described.

-Wes
